/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#09241b",
        "on-secondary-fixed": "#4c2e00",
        "inverse-primary": "#006d4a",
        "surface-dim": "#01120b",
        "surface-bright": "#123227",
        "on-tertiary-fixed": "#004b33",
        "secondary-container": "#855300",
        "primary-dim": "#58e7ab",
        "tertiary-fixed": "#6bffc1",
        "surface": "#01120b",
        "secondary-fixed-dim": "#ffb554",
        "on-tertiary-container": "#006042",
        "inverse-surface": "#e7fff2",
        "secondary-fixed": "#ffc885",
        "tertiary-fixed-dim": "#5af0b4",
        "surface-variant": "#0d2b21",
        "primary-fixed": "#69f6b8",
        "on-tertiary": "#006948",
        "on-primary-container": "#002919",
        "on-secondary-fixed-variant": "#724700",
        "error": "#ff716c",
        "error-dim": "#d7383b",
        "surface-container-highest": "#0d2b21",
        "on-primary": "#005a3c",
        "on-error": "#490006",
        "on-error-container": "#ffa8a3",
        "on-secondary": "#4a2c00",
        "tertiary-dim": "#5af0b4",
        "secondary": "#f8a010",
        "surface-container-lowest": "#000000",
        "on-background": "#e4fcf0",
        "surface-tint": "#69f6b8",
        "surface-container-low": "#021710",
        "outline": "#657a70",
        "on-surface": "#e4fcf0",
        "on-primary-fixed": "#00452d",
        "outline-variant": "#384c43",
        "tertiary-container": "#6bffc1",
        "surface-container": "#051e15",
        "primary": "#69f6b8",
        "primary-fixed-dim": "#58e7ab",
        "background": "#01120b",
        "on-tertiary-fixed-variant": "#006b4a",
        "primary-container": "#06b77f",
        "error-container": "#9f0519",
        "inverse-on-surface": "#455950",
        "on-surface-variant": "#9ab0a5",
        "secondary-dim": "#e79400",
        "on-secondary-container": "#fff6f0",
        "tertiary": "#cdffe3",
        "on-primary-fixed-variant": "#006544"
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans'],
        body: ['Plus Jakarta Sans'],
        label: ['Plus Jakarta Sans'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
