'use client'

import { useEffect, useState, useCallback, Fragment } from 'react'
import { useRouter } from 'next/navigation'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { toast } from 'sonner'
import { Sparkles, Target, Swords, FileText, Leaf, Pencil, ArrowLeft, Download, Copy, BookOpen, Trash2, Network, Loader2, Check, LayoutGrid, List, Printer, ExternalLink, X } from 'lucide-react'
import Segmented from '@/components/ui/v2/segmented'
import MermaidDiagram from '@/components/ui/mermaid-diagram'
import { readCache, writeCache } from '@/lib/swr-cache'

import Hero from '@/components/layout/hero'
import Header from '@/components/layout/header'
import BottomNav from '@/components/layout/bottom-nav'
import Pill from '@/components/ui/v2/pill'
import SectionHeader from '@/components/ui/v2/section-header'
import { THINKING_MODES } from '@/lib/thinking-modes'

// ── Types ─────────────────────────────────────────────

interface PRDItem {
  id: string
  title: string
  content: string
  createdAt: string
  source?: string
  local?: boolean
  diagramUrl?: string
  diagramMermaid?: string
  buildStatus?: string
  prUrl?: string
  autoGenerated?: boolean
  visionStatus?: string
}

interface SeedMeta {
  tags?: string[] | string
  seed_type?: string
  diagram_url?: string
  diagram_mermaid?: string
  build_status?: string
  build_pr_url?: string
  pdf_url?: string
  paper_url?: string
  source_url?: string
  digest_date?: string
  parse_status?: string
  chunk_count?: number
  auto_generated?: boolean
  vision_status?: string
}

// Older digest papers only stored source_url — derive the PDF link from the abs page
function paperPdfUrl(meta: SeedMeta): string {
  if (meta.pdf_url) return meta.pdf_url
  const src = meta.paper_url || meta.source_url || ''
  return src.includes('arxiv.org/abs/') ? src.replace('/abs/', '/pdf/') : ''
}

function isPaperSeed(s: RawSeed): boolean {
  const meta = s.seed_metadata || s.metadata || {}
  if ((s.seed_type || meta.seed_type) === 'paper') return true
  return normalizeTags(s).some(t => t === 'paper' || t === 'research-paper')
}

interface RawSeed {
  id?: string
  notion_id?: string
  title?: string
  content?: string
  text?: string
  summary?: string
  seed_type?: string
  type?: string
  tags?: string | string[]
  seed_metadata?: SeedMeta
  metadata?: SeedMeta
  created_at?: string
  created?: string
}

const BUILD_STATUS_LABELS: Record<string, string> = {
  draft: 'DRAFT',
  ready: 'READY',
  building: 'BUILDING',
  shipped: 'SHIPPED',
}

// Build pipeline stages — Design (draft/ready) → Doing (building) → Built (shipped)
const BUILD_STAGES = [
  { key: 'draft',    label: 'Design',  blurb: 'Spec being shaped' },
  { key: 'ready',    label: 'Ready',   blurb: 'Agent can pick this up' },
  { key: 'building', label: 'Doing',   blurb: 'Implementation underway' },
  { key: 'shipped',  label: 'Built',   blurb: 'Shipped — PR merged' },
]

// Drafts stay off the canvas — the board tracks specs that are actually in motion
const BOARD_COLUMNS = [
  { key: 'ready', label: 'Ready', statuses: ['ready'],    dropStatus: 'ready',    accent: 'var(--green-700)' },
  { key: 'doing', label: 'Doing', statuses: ['building'], dropStatus: 'building', accent: 'var(--amber)' },
  { key: 'built', label: 'Built', statuses: ['shipped'],  dropStatus: 'shipped',  accent: 'var(--green-600)' },
]

const isDraft = (p: PRDItem) => !p.buildStatus || p.buildStatus === 'draft'

// ── Build pipeline timeline (PRD detail) ─────────────

function BuildTimeline({ status, prUrl, onSelect }: { status: string; prUrl?: string; onSelect: (s: string) => void }) {
  const idx = Math.max(BUILD_STAGES.findIndex(s => s.key === status), 0)
  return (
    <div className="glass" style={{ borderRadius: 18, padding: '14px 18px 12px', marginBottom: 16 }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }}>
        <span className="caps" style={{ fontSize: 9.5, color: 'var(--ink-3)' }}>BUILD PIPELINE</span>
        {prUrl && (
          <a href={prUrl} target="_blank" rel="noopener noreferrer" className="ui" style={{ fontSize: 11, fontWeight: 600, color: 'var(--green-700)', textDecoration: 'none' }}>View PR →</a>
        )}
      </div>
      <div style={{ display: 'flex', alignItems: 'flex-start' }}>
        {BUILD_STAGES.map((s, i) => {
          const done = i < idx
          const current = i === idx
          return (
            <Fragment key={s.key}>
              {i > 0 && (
                <div style={{ flex: 1, height: 2, borderRadius: 99, background: i <= idx ? 'var(--green)' : 'var(--border-2)', marginTop: 11 }} />
              )}
              <button
                onClick={() => onSelect(s.key)}
                className="tap"
                title={s.blurb}
                style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '0 6px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, width: 64, flexShrink: 0 }}
              >
                <span style={{
                  width: 22, height: 22, borderRadius: 99, display: 'flex', alignItems: 'center', justifyContent: 'center',
                  background: done || current ? 'var(--green)' : 'var(--surface-sunk)',
                  border: current ? '2px solid var(--green-deep)' : '2px solid transparent',
                  boxShadow: current ? '0 0 0 4px var(--green-tint-2)' : 'none',
                  transition: 'all 0.2s ease',
                }}>
                  {done ? <Check size={12} color="#06281a" strokeWidth={3} /> : (
                    <span style={{ width: 7, height: 7, borderRadius: 99, background: current ? '#06281a' : 'var(--ink-3)' }} />
                  )}
                </span>
                <span className="ui" style={{ fontSize: 10.5, fontWeight: current ? 700 : 500, color: current ? 'var(--green-deep)' : done ? 'var(--ink-2)' : 'var(--ink-3)' }}>
                  {s.label}
                </span>
              </button>
            </Fragment>
          )
        })}
      </div>
    </div>
  )
}

// ── Helpers ───────────────────────────────────────────

const SPEC_TAGS = ['spec', 'prd', 'strategy-paper']

function normalizeTags(s: RawSeed): string[] {
  const raw = s.tags ?? s.seed_metadata?.tags ?? s.metadata?.tags ?? []
  const arr = Array.isArray(raw) ? raw : String(raw).split(',')
  return arr.map(t => t.trim().toLowerCase()).filter(Boolean)
}

function isSpecSeed(s: RawSeed): boolean {
  const type = (s.seed_type || s.type || '').toLowerCase()
  if (type === 'spec') return true
  const content = s.content || s.text || s.summary || ''
  // Must have meaningful PRD content (not just a short agent output)
  if (content.length < 500) return false
  return normalizeTags(s).some(t => SPEC_TAGS.includes(t))
}

function seedToPRD(s: RawSeed): PRDItem {
  const content = s.content || s.text || s.summary || ''
  const meta = s.seed_metadata || s.metadata || {}
  return {
    id: s.id || s.notion_id || `seed_${Math.random().toString(36).slice(2)}`,
    title: s.title || content.split('\n')[0]?.replace(/^#+\s*/, '').slice(0, 80) || 'Untitled spec',
    content, createdAt: s.created_at || s.created || new Date().toISOString(), source: 'garden',
    diagramUrl: meta.diagram_url, diagramMermaid: meta.diagram_mermaid, buildStatus: meta.build_status, prUrl: meta.build_pr_url,
    autoGenerated: !!meta.auto_generated, visionStatus: meta.vision_status,
  }
}

// Hand an auto-draft to the thinking partner for the vision interrogation
function shapeVision(prd: PRDItem, router: ReturnType<typeof useRouter>) {
  try {
    localStorage.setItem('greenplot_spec_prefill', JSON.stringify({
      id: prd.id, title: prd.title, content: prd.content, vision: true,
    }))
  } catch {}
  router.push('/chat?mode=spec')
}

function timeAgo(date: string): string {
  const diff = Date.now() - new Date(date).getTime()
  const mins = Math.floor(diff / 60000)
  if (mins < 60) return `${Math.max(mins, 0)}m ago`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24) return `${hrs}h ago`
  return `${Math.floor(hrs / 24)}d ago`
}

function loadLocalPRDs(): PRDItem[] {
  try {
    const raw = localStorage.getItem('greenplot_prds')
    if (!raw) return []
    const list = JSON.parse(raw)
    return Array.isArray(list) ? list.map((p: PRDItem) => ({ ...p, local: true })) : []
  } catch { return [] }
}

// Lucide icon mapped to mode id
const MODE_ICONS: Record<string, React.ComponentType<any>> = {
  brainstorm: Sparkles,
  challenge: Target,
  strategize: Swords,
  spec: FileText,
}

// ── Idea / Paper Detail ───────────────────────────────

function IdeaDetail({ seed, onBack, onSpec, onDrafted }: { seed: RawSeed; onBack: () => void; onSpec: () => void; onDrafted?: () => void }) {
  const meta = seed.seed_metadata || seed.metadata || {}
  const paper = isPaperSeed(seed)
  const pdfUrl = paperPdfUrl(meta)
  const paperUrl = meta.paper_url || ''
  const content = seed.content || seed.text || seed.summary || ''
  const [pdfOpen, setPdfOpen] = useState(!!pdfUrl)
  const [draftState, setDraftState] = useState<'idle' | 'drafting' | 'success' | 'error'>('idle')
  const [draftTitle, setDraftTitle] = useState('')
  const [draftError, setDraftError] = useState('')
  const drafting = draftState === 'drafting'

  // Poll the paper seed's metadata until the background job records an outcome
  const pollOutcome = (token: string | null) => {
    const started = Date.now()
    const tick = async () => {
      if (Date.now() - started > 180_000) {
        setDraftError('Taking longer than expected — check the Build pipeline drafts in a few minutes.')
        setDraftState('error')
        return
      }
      try {
        const res = await fetch(`/api/seeds/${seed.id}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} })
        if (res.ok) {
          const data = await res.json()
          const m = data.seed_metadata || data.metadata || {}
          const status: string = m.auto_prd || ''
          if (status === 'drafted' && m.draft_prd_id) {
            setDraftTitle(m.draft_prd_title || 'Draft PRD')
            setDraftState('success')
            onDrafted?.()
            return
          }
          if (status.startsWith('error') || status.startsWith('skipped')) {
            setDraftError(
              status.includes('insufficient_context')
                ? 'Not enough parsed content yet — the paper needs at least 3 indexed sections and 2 related seeds.'
                : m.draft_prd_error || status.replace(/_/g, ' ')
            )
            setDraftState('error')
            return
          }
        }
      } catch {}
      setTimeout(tick, 5000)
    }
    setTimeout(tick, 8000)
  }

  const draftPrd = async () => {
    if (drafting || !seed.id) return
    setDraftState('drafting')
    setDraftError('')
    try {
      const token = localStorage.getItem('greenplot_token')
      const res = await fetch(`/api/papers/${seed.id}/draft-prd`, {
        method: 'POST',
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
      const data = await res.json()
      if (res.ok) {
        pollOutcome(token)
      } else {
        setDraftError(data.detail || data.error || 'Could not start draft generation')
        setDraftState('error')
      }
    } catch {
      setDraftError('Could not reach the server')
      setDraftState('error')
    }
  }
  const [parseStatus, setParseStatus] = useState(meta.parse_status || '')
  const [indexing, setIndexing] = useState(false)

  const indexFullText = async () => {
    if (indexing || !seed.id) return
    setIndexing(true)
    try {
      const token = localStorage.getItem('greenplot_token')
      const res = await fetch(`/api/papers/${seed.id}/parse`, {
        method: 'POST',
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
      const data = await res.json()
      if (res.ok) {
        setParseStatus(data.status === 'ok' ? 'parsed' : 'parsing')
        toast.success(data.status === 'ok'
          ? `Full text indexed — ${data.chunks} chunks`
          : 'Full-text indexing queued — ready in a minute')
      } else {
        toast.error(data.detail || data.error || 'Could not index paper')
      }
    } catch {
      toast.error('Could not index paper')
    } finally {
      setIndexing(false)
    }
  }

  return (
    <div className="print-root" style={{ background: 'var(--bg)', height: '100dvh', overflowY: 'auto', overflowX: 'hidden' }}>
      <div className="print:hidden" style={{ position: 'fixed', top: 0, left: 'var(--sidenav-w, 0px)', right: 0, zIndex: 50, background: 'rgba(250,249,246,0.92)', backdropFilter: 'blur(16px)', paddingTop: 'env(safe-area-inset-top, 0px)', borderBottom: '1px solid var(--hairline)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '12px 18px', height: 56 }}>
          <button onClick={onBack} className="tap" style={{ background: 'none', border: 'none', display: 'flex', alignItems: 'center', gap: 6, color: 'var(--green-700)', fontFamily: 'var(--ui)', fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>
            <ArrowLeft size={18} strokeWidth={2} color="var(--green-700)" /> Studio
          </button>
          <div style={{ flex: 1 }} />
          {paperUrl && (
            <a href={paperUrl} target="_blank" rel="noopener noreferrer" className="tap" style={{ display: 'flex', alignItems: 'center', gap: 5, color: 'var(--ink-2)', fontFamily: 'var(--ui)', fontSize: 12, fontWeight: 600, textDecoration: 'none', padding: '7px 10px' }}>
              <ExternalLink size={13} strokeWidth={2} /> arXiv
            </a>
          )}
          {paper && (
            <button onClick={draftPrd} disabled={drafting} className="tap" style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'var(--green-tint)', color: 'var(--green-700)', border: 'none', borderRadius: 9999, padding: '7px 13px', fontFamily: 'var(--ui)', fontSize: 12, fontWeight: 700, cursor: 'pointer', opacity: drafting ? 0.6 : 1 }}>
              {drafting ? <Loader2 size={13} strokeWidth={2} className="animate-spin" /> : <FileText size={13} strokeWidth={2} />} Draft PRD
            </button>
          )}
          <button onClick={onSpec} className="tap" style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'var(--green)', color: '#06281a', border: 'none', borderRadius: 9999, padding: '7px 15px', fontFamily: 'var(--ui)', fontSize: 12, fontWeight: 700, cursor: 'pointer' }}>
            <Pencil size={13} strokeWidth={2} /> Spec it
          </button>
        </div>
      </div>

      <div className="desk-narrow" style={{ paddingBottom: 100, padding: '0 18px' }}>
        <div style={{ paddingTop: 'calc(56px + env(safe-area-inset-top, 0px) + 24px)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
            <Pill tone="soft" size="xs">{paper ? 'PAPER' : 'IDEA'}</Pill>
            {meta.digest_date && (
              <span className="body-text" style={{ fontSize: 10.5, color: 'var(--ink-3)' }}>Research Digest · {meta.digest_date}</span>
            )}
            {paper && (
              parseStatus === 'parsed' ? (
                <span className="ui" style={{ fontSize: 9, fontWeight: 700, letterSpacing: '0.06em', color: 'var(--green-700)', background: 'var(--green-tint)', borderRadius: 9999, padding: '2px 8px' }}>
                  FULL TEXT INDEXED{meta.chunk_count ? ` · ${meta.chunk_count} CHUNKS` : ''}
                </span>
              ) : parseStatus === 'parsing' ? (
                <span className="ui" style={{ fontSize: 9, fontWeight: 700, letterSpacing: '0.06em', color: 'var(--amber)', background: 'rgba(201,138,27,0.12)', borderRadius: 9999, padding: '2px 8px' }}>
                  INDEXING…
                </span>
              ) : (
                <button onClick={indexFullText} disabled={indexing} className="tap ui" style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 9, fontWeight: 700, letterSpacing: '0.06em', color: 'var(--ink-2)', background: 'var(--surface-sunk)', border: '1px solid var(--border-2)', borderRadius: 9999, padding: '2px 8px', cursor: 'pointer' }}>
                  {indexing ? <Loader2 size={9} className="animate-spin" /> : null}
                  {parseStatus === 'failed' ? 'RETRY FULL-TEXT INDEX' : 'INDEX FULL TEXT'}
                </button>
              )
            )}
          </div>
          <h1 className="serif" style={{ fontSize: 28, lineHeight: 1.15, color: 'var(--ink)', marginTop: 12, marginBottom: 16, letterSpacing: '-0.02em' }}>
            {seed.title || 'Untitled'}
          </h1>

          {/* Digest description / idea content — the connection to your garden */}
          <div className="glass" style={{ borderRadius: 20, padding: '18px 22px', marginBottom: 16 }}>
            <div className="prose prose-sm max-w-none" style={{ fontFamily: 'var(--body)', fontSize: 14.5, lineHeight: 1.7, color: 'var(--ink-2)' }}>
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown>
            </div>
          </div>

          {/* Embedded PDF */}
          {pdfUrl && (
            <div style={{ borderRadius: 20, overflow: 'hidden', border: '1px solid var(--hairline)', marginBottom: 16 }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 14px', background: 'var(--surface-sunk)' }}>
                <span className="ui" style={{ fontSize: 12, fontWeight: 700, color: 'var(--ink)' }}>📄 Paper PDF</span>
                <div style={{ display: 'flex', gap: 12 }}>
                  <button onClick={() => setPdfOpen(o => !o)} className="tap ui" style={{ background: 'none', border: 'none', fontSize: 11, fontWeight: 600, color: 'var(--green-700)', cursor: 'pointer' }}>
                    {pdfOpen ? 'Collapse' : 'Expand'}
                  </button>
                  <a href={pdfUrl} target="_blank" rel="noopener noreferrer" className="ui" style={{ fontSize: 11, fontWeight: 600, color: 'var(--green-700)', textDecoration: 'none' }}>
                    Open in new tab ↗
                  </a>
                </div>
              </div>
              {pdfOpen && (
                <iframe
                  src={pdfUrl}
                  title="Paper PDF"
                  style={{ width: '100%', height: '72vh', border: 'none', display: 'block', background: '#fff' }}
                />
              )}
            </div>
          )}
        </div>
      </div>

      {/* Draft-PRD progress / outcome modal */}
      {draftState !== 'idle' && (
        <div style={{ position: 'fixed', inset: 0, zIndex: 80, background: 'rgba(10,38,24,0.45)', backdropFilter: 'blur(6px)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}>
          <div className="glass" style={{ borderRadius: 24, padding: '28px 26px', maxWidth: 400, width: '100%', textAlign: 'center', background: 'rgba(255,255,255,0.95)' }}>
            {draftState === 'drafting' && (
              <>
                <div style={{ width: 52, height: 52, borderRadius: 99, border: '3px solid var(--green-tint-2)', borderTopColor: 'var(--green)', animation: 'spin 0.9s linear infinite', margin: '0 auto 18px' }} />
                <h3 className="serif" style={{ fontSize: 22, color: 'var(--ink)', marginBottom: 8 }}>Drafting your PRD</h3>
                <p className="body-text" style={{ fontSize: 13, color: 'var(--ink-2)', lineHeight: 1.6, marginBottom: 20 }}>
                  Reading the paper's parsed sections and your related seeds, then writing a full gstack PRD. Usually ~1 minute.
                </p>
                <button onClick={() => setDraftState('idle')} className="tap ui" style={{ background: 'none', border: 'none', fontSize: 12, fontWeight: 600, color: 'var(--ink-3)', cursor: 'pointer' }}>
                  Continue in background
                </button>
              </>
            )}
            {draftState === 'success' && (
              <>
                <div style={{ width: 52, height: 52, borderRadius: 99, background: 'var(--green)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 18px' }}>
                  <Check size={28} color="#06281a" strokeWidth={3} />
                </div>
                <h3 className="serif" style={{ fontSize: 22, color: 'var(--ink)', marginBottom: 8 }}>Draft PRD created</h3>
                <p className="ui" style={{ fontSize: 13.5, fontWeight: 700, color: 'var(--green-deep)', marginBottom: 6 }}>{draftTitle}</p>
                <p className="body-text" style={{ fontSize: 12.5, color: 'var(--ink-2)', lineHeight: 1.6, marginBottom: 20 }}>
                  It's waiting in your Build pipeline drafts — shape the vision when you're ready.
                </p>
                <div style={{ display: 'flex', gap: 9, justifyContent: 'center' }}>
                  <button onClick={() => setDraftState('idle')} className="tap ui" style={{ background: 'var(--surface-sunk)', border: 'none', borderRadius: 9999, padding: '10px 18px', fontSize: 12.5, fontWeight: 600, color: 'var(--ink-2)', cursor: 'pointer' }}>
                    Stay here
                  </button>
                  <button onClick={() => { setDraftState('idle'); onBack() }} className="tap ui" style={{ background: 'var(--green)', border: 'none', borderRadius: 9999, padding: '10px 18px', fontSize: 12.5, fontWeight: 700, color: '#06281a', cursor: 'pointer' }}>
                    View in drafts →
                  </button>
                </div>
              </>
            )}
            {draftState === 'error' && (
              <>
                <div style={{ width: 52, height: 52, borderRadius: 99, background: 'rgba(212,80,62,0.12)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 18px' }}>
                  <X size={26} color="var(--red)" strokeWidth={2.5} />
                </div>
                <h3 className="serif" style={{ fontSize: 22, color: 'var(--ink)', marginBottom: 8 }}>Couldn't draft the PRD</h3>
                <p className="body-text" style={{ fontSize: 12.5, color: 'var(--ink-2)', lineHeight: 1.6, marginBottom: 20 }}>{draftError}</p>
                <div style={{ display: 'flex', gap: 9, justifyContent: 'center' }}>
                  <button onClick={() => setDraftState('idle')} className="tap ui" style={{ background: 'var(--surface-sunk)', border: 'none', borderRadius: 9999, padding: '10px 18px', fontSize: 12.5, fontWeight: 600, color: 'var(--ink-2)', cursor: 'pointer' }}>
                    Close
                  </button>
                  <button onClick={draftPrd} className="tap ui" style={{ background: 'var(--green)', border: 'none', borderRadius: 9999, padding: '10px 18px', fontSize: 12.5, fontWeight: 700, color: '#06281a', cursor: 'pointer' }}>
                    Try again
                  </button>
                </div>
              </>
            )}
          </div>
          <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
        </div>
      )}
    </div>
  )
}

// ── PRD Detail ────────────────────────────────────────

function PRDDetail({ prd, onBack, onDeleted, onStatusChanged, onUpdated }: { prd: PRDItem; onBack: () => void; onDeleted: (id: string) => void; onStatusChanged?: (id: string, status: string) => void; onUpdated?: (id: string, patch: Partial<PRDItem>) => void }) {
  const router = useRouter()
  const [diagramUrl] = useState(prd.diagramUrl)
  const [diagramMermaid, setDiagramMermaid] = useState(prd.diagramMermaid)
  const [generating, setGenerating] = useState(false)
  const [buildStatus, setBuildStatus] = useState(prd.buildStatus || 'draft')
  const [editing, setEditing] = useState(false)
  const [editTitle, setEditTitle] = useState(prd.title)
  const [editContent, setEditContent] = useState(prd.content)
  const [title, setTitle] = useState(prd.title)
  const [content, setContent] = useState(prd.content)
  const [saving, setSaving] = useState(false)

  const generateDiagram = async () => {
    if (generating) return
    setGenerating(true)
    try {
      const token = localStorage.getItem('greenplot_token')
      // Mermaid code from the text model — deterministic render with real
      // labels (BFL raster diagrams garbled text and structure)
      const res = await fetch(`/api/specs/${prd.id}/diagram-code`, {
        method: 'POST',
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
      const data = await res.json()
      if (res.ok && data.mermaid) {
        setDiagramMermaid(data.mermaid)
        // Persist into the list state so reopening the PRD keeps the diagram
        onUpdated?.(prd.id, { diagramMermaid: data.mermaid })
        toast.success('Architecture diagram generated')
      } else {
        toast.error(data.detail || data.error || 'Diagram generation failed')
      }
    } catch {
      toast.error('Diagram generation failed')
    } finally {
      setGenerating(false)
    }
  }

  const saveEdits = async () => {
    const newTitle = editTitle.trim()
    const newContent = editContent.trim()
    if (!newTitle || !newContent || saving) return
    setSaving(true)
    try {
      if (prd.local) {
        // Local drafts live in localStorage only
        const raw = localStorage.getItem('greenplot_prds')
        const list: PRDItem[] = raw ? JSON.parse(raw) : []
        localStorage.setItem('greenplot_prds', JSON.stringify(list.map(p => p.id === prd.id ? { ...p, title: newTitle, content: newContent } : p)))
      } else {
        const token = localStorage.getItem('greenplot_token')
        const res = await fetch(`/api/seeds/${prd.id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
          body: JSON.stringify({ title: newTitle, content: newContent }),
        })
        if (!res.ok) {
          const data = await res.json().catch(() => ({}))
          throw new Error(data.detail || data.error || 'Save failed')
        }
      }
      setTitle(newTitle)
      setContent(newContent)
      onUpdated?.(prd.id, { title: newTitle, content: newContent })
      setEditing(false)
      toast.success('PRD saved')
    } catch (e) {
      toast.error((e as Error).message || 'Could not save — backend update pending')
    } finally {
      setSaving(false)
    }
  }

  const exportPdf = () => {
    // Print stylesheet hides app chrome (print:hidden) and .print-root
    // removes the 100dvh clip so the whole document paginates
    window.print()
  }

  const setStage = async (next: string) => {
    if (next === buildStatus) return
    const prev = buildStatus
    setBuildStatus(next)
    try {
      const token = localStorage.getItem('greenplot_token')
      const res = await fetch(`/api/specs/${prd.id}/build-status`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
        body: JSON.stringify({ status: next }),
      })
      if (res.ok) {
        toast.success(`Moved to ${BUILD_STAGES.find(s => s.key === next)?.label || next}`)
        onStatusChanged?.(prd.id, next)
      } else {
        setBuildStatus(prev)
        toast.error('Could not update — backend update pending')
      }
    } catch {
      setBuildStatus(prev)
      toast.error('Could not update status')
    }
  }

  const copyForAgent = () => {
    const framed = `# ${title}\n\n${content}\n\n---\nUse this PRD as the spec for the task I'm about to describe. Implement it faithfully, asking before making scope decisions not covered above.`
    navigator.clipboard.writeText(framed)
    toast.success('Copied — paste into Claude Code')
  }

  const downloadMd = () => {
    const blob = new Blob([`# ${title}\n\n${content}\n`], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url
    a.download = `${title.replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 60)}.md`
    a.click(); URL.revokeObjectURL(url)
  }

  const deleteLocal = () => {
    try {
      const raw = localStorage.getItem('greenplot_prds')
      const list = raw ? JSON.parse(raw) : []
      localStorage.setItem('greenplot_prds', JSON.stringify((list as PRDItem[]).filter(p => p.id !== prd.id)))
    } catch {}
    toast.success('PRD deleted')
    onDeleted(prd.id)
  }

  return (
    <div className="print-root" style={{ background: 'var(--bg)', height: '100dvh', overflowY: 'auto', overflowX: 'hidden' }}>
      {/* Minimal header */}
      <div className="print:hidden" style={{ position: 'fixed', top: 0, left: 'var(--sidenav-w, 0px)', right: 0, zIndex: 50, background: 'rgba(250,249,246,0.92)', backdropFilter: 'blur(16px)', paddingTop: 'env(safe-area-inset-top, 0px)', borderBottom: '1px solid var(--hairline)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '12px 18px', height: 56 }}>
          <button onClick={onBack} className="tap" style={{ background: 'none', border: 'none', display: 'flex', alignItems: 'center', gap: 6, color: 'var(--green-700)', fontFamily: 'var(--ui)', fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>
            <ArrowLeft size={18} strokeWidth={2} color="var(--green-700)" /> Studio
          </button>
          <div style={{ flex: 1 }} />
          {editing ? (
            <>
              <button onClick={() => { setEditing(false); setEditTitle(title); setEditContent(content) }} className="tap" style={{ background: 'none', border: 'none', color: 'var(--ink-2)', fontFamily: 'var(--ui)', fontSize: 12, fontWeight: 600, cursor: 'pointer', padding: '7px 10px' }}>
                Cancel
              </button>
              <button onClick={saveEdits} disabled={saving} className="tap" style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'var(--green)', color: '#06281a', border: 'none', borderRadius: 9999, padding: '7px 15px', fontFamily: 'var(--ui)', fontSize: 12, fontWeight: 700, cursor: 'pointer', opacity: saving ? 0.6 : 1 }}>
                {saving ? <Loader2 size={13} strokeWidth={2} className="animate-spin" /> : <Check size={13} strokeWidth={2.5} />} Save
              </button>
            </>
          ) : (
            <>
              {prd.autoGenerated && prd.visionStatus !== 'shaped' && (
                <button onClick={() => shapeVision({ ...prd, title, content }, router)} className="tap" style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'var(--green)', color: '#06281a', border: 'none', borderRadius: 9999, padding: '7px 15px', fontFamily: 'var(--ui)', fontSize: 12, fontWeight: 700, cursor: 'pointer' }}>
                  <Sparkles size={13} strokeWidth={2} /> Shape the vision
                </button>
              )}
              <button onClick={copyForAgent} className="tap" style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'var(--green-tint)', color: 'var(--green-700)', border: 'none', borderRadius: 9999, padding: '7px 13px', fontFamily: 'var(--ui)', fontSize: 12, fontWeight: 700, cursor: 'pointer' }}>
                <Copy size={13} strokeWidth={2} /> Copy for Claude Code
              </button>
              <button onClick={() => setEditing(true)} className="tap" title="Edit PRD" style={{ background: 'none', border: 'none', padding: 8, cursor: 'pointer' }}>
                <Pencil size={16} strokeWidth={1.75} color="var(--ink-2)" />
              </button>
              <button onClick={exportPdf} className="tap" title="Export as PDF" style={{ background: 'none', border: 'none', padding: 8, cursor: 'pointer' }}>
                <Printer size={16} strokeWidth={1.75} color="var(--ink-2)" />
              </button>
              <button onClick={downloadMd} className="tap" title="Download markdown" style={{ background: 'none', border: 'none', padding: 8, cursor: 'pointer' }}>
                <Download size={16} strokeWidth={1.75} color="var(--ink-2)" />
              </button>
              {prd.local && (
                <button onClick={deleteLocal} className="tap" style={{ background: 'none', border: 'none', padding: 8, cursor: 'pointer' }}>
                  <Trash2 size={16} strokeWidth={1.75} color="var(--red)" />
                </button>
              )}
            </>
          )}
        </div>
      </div>

      <div className="desk-narrow" style={{ paddingTop: 'calc(56px + env(safe-area-inset-top, 0px) + 24px)', paddingBottom: 100, padding: '0 18px' }}>
        <div style={{ paddingTop: 'calc(56px + env(safe-area-inset-top, 0px) + 24px)' }}>
          <span className="print:hidden"><Pill tone="soft" size="xs">SPEC</Pill></span>
          {editing ? (
            <input
              value={editTitle}
              onChange={(e) => setEditTitle(e.target.value)}
              className="serif"
              style={{ width: '100%', fontSize: 32, lineHeight: 1.1, color: 'var(--ink)', marginTop: 12, marginBottom: 8, letterSpacing: '-0.02em', background: 'var(--surface-sunk)', border: '1px solid var(--border-2)', borderRadius: 12, padding: '6px 12px', outline: 'none' }}
            />
          ) : (
            <h1 className="serif" style={{ fontSize: 32, lineHeight: 1.1, color: 'var(--ink)', marginTop: 12, marginBottom: 8, letterSpacing: '-0.02em' }}>{title}</h1>
          )}
          <p className="body-text print:hidden" style={{ fontSize: 11, color: 'var(--ink-3)', marginBottom: 20 }}>
            {prd.local ? 'Saved from Spec mode' : 'From your garden'} · {timeAgo(prd.createdAt)}
          </p>
          {!prd.local && !editing && (
            <div className="print:hidden">
              <BuildTimeline status={buildStatus} prUrl={prd.prUrl} onSelect={setStage} />
            </div>
          )}
          {!prd.local && !editing && diagramMermaid && (
            <div style={{ borderRadius: 20, overflow: 'hidden', border: '1px solid var(--hairline)', marginBottom: 16, background: '#fff' }}>
              <MermaidDiagram code={diagramMermaid} id={prd.id} />
              <div className="print:hidden" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 14px', background: 'var(--surface-sunk)' }}>
                <span className="body-text" style={{ fontSize: 10.5, color: 'var(--ink-3)' }}>System architecture · generated from the spec</span>
                <button onClick={generateDiagram} disabled={generating} className="tap ui" style={{ background: 'none', border: 'none', fontSize: 11, fontWeight: 600, color: 'var(--green-700)', cursor: 'pointer' }}>
                  {generating ? 'Regenerating…' : 'Regenerate'}
                </button>
              </div>
            </div>
          )}
          {!prd.local && !editing && !diagramMermaid && (
            diagramUrl ? (
              <div style={{ borderRadius: 20, overflow: 'hidden', border: '1px solid var(--hairline)', marginBottom: 16 }}>
                <img src={diagramUrl} alt="System architecture diagram" style={{ width: '100%', height: 'auto', display: 'block' }} loading="lazy" />
                <div className="print:hidden" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 14px', background: 'var(--surface-sunk)' }}>
                  <span className="body-text" style={{ fontSize: 10.5, color: 'var(--ink-3)' }}>System architecture · BFL Flux</span>
                  <button onClick={generateDiagram} disabled={generating} className="tap ui" style={{ background: 'none', border: 'none', fontSize: 11, fontWeight: 600, color: 'var(--green-700)', cursor: 'pointer' }}>
                    {generating ? 'Regenerating…' : 'Regenerate'}
                  </button>
                </div>
              </div>
            ) : (
              <button onClick={generateDiagram} disabled={generating} className="tap print:hidden" style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', justifyContent: 'center', background: 'var(--green-tint)', color: 'var(--green-700)', border: '1px dashed var(--green-tint-2)', borderRadius: 16, padding: '13px 16px', fontFamily: 'var(--ui)', fontSize: 12.5, fontWeight: 700, cursor: 'pointer', marginBottom: 16 }}>
                {generating ? <Loader2 size={15} strokeWidth={2} className="animate-spin" /> : <Network size={15} strokeWidth={2} />}
                {generating ? 'Generating architecture diagram (~30s)…' : 'Generate architecture diagram'}
              </button>
            )
          )}
          {editing ? (
            <textarea
              value={editContent}
              onChange={(e) => setEditContent(e.target.value)}
              spellCheck={false}
              style={{ width: '100%', minHeight: '60vh', fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: 13, lineHeight: 1.7, color: 'var(--ink)', background: 'var(--surface-sunk)', border: '1px solid var(--border-2)', borderRadius: 16, padding: '16px 18px', outline: 'none', resize: 'vertical' }}
            />
          ) : (
            <div className="glass" style={{ borderRadius: 20, padding: '20px 24px' }}>
              <div className="prd-prose" style={{ fontFamily: 'var(--body)', fontSize: 15, lineHeight: 1.7, color: 'var(--ink)' }}>
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{
                    h1: ({ children }) => <h1 className="serif" style={{ fontSize: 24, lineHeight: 1.2, color: 'var(--ink)', margin: '6px 0 14px' }}>{children}</h1>,
                    h2: ({ children }) => (
                      <h2 className="ui" style={{ fontSize: 15, fontWeight: 700, color: 'var(--green-deep)', margin: '26px 0 10px', paddingBottom: 7, borderBottom: '2px solid var(--green-tint-2)', letterSpacing: '-0.01em' }}>{children}</h2>
                    ),
                    h3: ({ children }) => <h3 className="ui" style={{ fontSize: 13.5, fontWeight: 700, color: 'var(--ink)', margin: '18px 0 7px' }}>{children}</h3>,
                    p: ({ children }) => <p style={{ margin: '0 0 12px', color: 'var(--ink-2)' }}>{children}</p>,
                    ul: ({ children }) => <ul style={{ margin: '0 0 12px', paddingLeft: 22, color: 'var(--ink-2)', listStyleType: 'disc' }}>{children}</ul>,
                    ol: ({ children }) => <ol style={{ margin: '0 0 12px', paddingLeft: 22, color: 'var(--ink-2)', listStyleType: 'decimal' }}>{children}</ol>,
                    li: ({ children }) => <li style={{ margin: '4px 0' }}>{children}</li>,
                    strong: ({ children }) => <strong style={{ color: 'var(--ink)', fontWeight: 650 }}>{children}</strong>,
                    code: ({ children }) => <code style={{ background: 'var(--surface-sunk)', borderRadius: 6, padding: '1.5px 6px', fontSize: 12.5, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace' }}>{children}</code>,
                    blockquote: ({ children }) => <blockquote style={{ borderLeft: '3px solid var(--green-tint-2)', margin: '0 0 12px', padding: '4px 0 4px 14px', color: 'var(--ink-2)' }}>{children}</blockquote>,
                    table: ({ children }) => <div style={{ overflowX: 'auto', margin: '0 0 12px' }}><table style={{ borderCollapse: 'collapse', width: '100%', fontSize: 13 }}>{children}</table></div>,
                    th: ({ children }) => <th style={{ textAlign: 'left', padding: '7px 10px', borderBottom: '2px solid var(--border-2)', fontFamily: 'var(--ui)', fontSize: 11.5, fontWeight: 700, color: 'var(--ink)' }}>{children}</th>,
                    td: ({ children }) => <td style={{ padding: '7px 10px', borderBottom: '1px solid var(--hairline)', color: 'var(--ink-2)' }}>{children}</td>,
                    hr: () => <hr style={{ border: 'none', borderTop: '1px solid var(--hairline)', margin: '20px 0' }} />,
                  }}
                >
                  {content}
                </ReactMarkdown>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Page ──────────────────────────────────────────────

const PRD_PAGE_SIZE = 10

export default function StudioPage() {
  const router = useRouter()
  const [prds, setPrds] = useState<PRDItem[]>([])
  const [ideas, setIdeas] = useState<RawSeed[]>([])
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState<PRDItem | null>(null)
  const [selectedIdea, setSelectedIdea] = useState<RawSeed | null>(null)
  const [showAllPrds, setShowAllPrds] = useState(false)
  const [prdView, setPrdView] = useState<'board' | 'list'>('board')
  const [dragOverCol, setDragOverCol] = useState<string | null>(null)
  const [refreshKey, setRefreshKey] = useState(0)

  const updatePrdStatus = useCallback(async (id: string, status: string) => {
    let prev: string | undefined
    setPrds(p => p.map(x => { if (x.id === id) { prev = x.buildStatus; return { ...x, buildStatus: status } } return x }))
    try {
      const token = localStorage.getItem('greenplot_token')
      const res = await fetch(`/api/specs/${id}/build-status`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
        body: JSON.stringify({ status }),
      })
      if (!res.ok) throw new Error()
      toast.success(`Moved to ${BUILD_STAGES.find(s => s.key === status)?.label || status}`)
    } catch {
      setPrds(p => p.map(x => x.id === id ? { ...x, buildStatus: prev } : x))
      toast.error('Could not update — backend update pending')
    }
  }, [])

  const launchMode = useCallback((id: string) => router.push(`/chat?mode=${id}`), [router])

  const developSeed = useCallback((seed: RawSeed) => {
    try {
      localStorage.setItem('greenplot_spec_prefill', JSON.stringify({
        id: seed.id, title: seed.title,
        content: seed.content || seed.text || seed.summary || '',
      }))
    } catch {}
    router.push('/chat?mode=spec')
  }, [router])

  useEffect(() => {
    const local = loadLocalPRDs()
    setPrds(local)

    const applySeeds = (seeds: RawSeed[]) => {
      const specSeeds = seeds.filter(isSpecSeed).map(seedToPRD)
      const seen = new Set(local.map(p => p.id))
      setPrds([...local, ...specSeeds.filter(p => !seen.has(p.id))])
      // Papers from the Research Digest lead the "Ideas ready to develop" list —
      // they arrive pre-connected to the garden and are the strongest spec material
      const nonSpec = seeds.filter(s => !isSpecSeed(s) && (s.content || s.text || s.summary))
      setIdeas([...nonSpec.filter(isPaperSeed), ...nonSpec.filter(s => !isPaperSeed(s))].slice(0, 4))
    }

    // Stale-while-revalidate: paint cached seeds instantly, refresh in background
    const cached = readCache<{ seeds?: RawSeed[] }>('seeds')
    if (cached?.seeds?.length) {
      applySeeds(cached.seeds)
      setLoading(false)
    }

    const token = localStorage.getItem('greenplot_token')
    fetch('/api/seeds?limit=200', { headers: token ? { Authorization: `Bearer ${token}` } : {} })
      .then(r => {
        if (r.status === 401) { localStorage.removeItem('greenplot_token'); window.location.href = '/login'; return { seeds: [] } }
        return r.json()
      })
      .then((data: { seeds?: RawSeed[]; total?: number }) => {
        const seeds = data.seeds || []
        applySeeds(seeds)
        if (seeds.length) writeCache('seeds', { seeds, total: data.total })
      })
      .catch(() => {})
      .finally(() => setLoading(false))
  // refreshKey re-runs the fetch after a manual Draft PRD generation
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [refreshKey])

  const handleDeleted = (id: string) => { setPrds(prev => prev.filter(p => p.id !== id)); setSelected(null) }

  if (selectedIdea) {
    return (
      <IdeaDetail
        seed={selectedIdea}
        onBack={() => setSelectedIdea(null)}
        onSpec={() => developSeed(selectedIdea)}
        onDrafted={() => setRefreshKey(k => k + 1)}
      />
    )
  }

  if (selected) {
    return (
      <PRDDetail
        prd={selected}
        onBack={() => setSelected(null)}
        onDeleted={handleDeleted}
        onStatusChanged={(id, status) => setPrds(prev => prev.map(p => p.id === id ? { ...p, buildStatus: status } : p))}
        onUpdated={(id, patch) => {
          setPrds(prev => prev.map(p => p.id === id ? { ...p, ...patch } : p))
          setSelected(prev => (prev && prev.id === id ? { ...prev, ...patch } : prev))
        }}
      />
    )
  }

  return (
    <div style={{ background: 'var(--bg)', height: '100dvh', overflowY: 'auto', overflowX: 'hidden' }}>
      <Header />

      <Hero
        eyebrow="YOUR THINKING PARTNER"
        title="The"
        accent="Studio"
        subtitle="Brainstorm, pressure-test, and spec ideas into PRDs you can hand to Claude Code."
      />

      <div className="desk-wrap" style={{ position: 'relative', zIndex: 3, marginTop: -22, padding: '0 18px', paddingBottom: 120 }}>
        <SectionHeader>Thinking partner</SectionHeader>

        {/* 2×2 mode grid (1×4 on desktop) */}
        <div style={{ display: 'grid', gridTemplateColumns: 'var(--desk-cols-4)', gap: 11 }}>
          {THINKING_MODES.map((mode) => {
            const ModeIcon = MODE_ICONS[mode.id] || Sparkles
            return (
              <button
                key={mode.id}
                onClick={() => launchMode(mode.id)}
                className="v2-card tap rise"
                style={{ textAlign: 'left', borderRadius: 18, padding: 15, cursor: 'pointer', display: 'flex', flexDirection: 'column', gap: 9, border: 'none' }}
              >
                <span style={{ width: 40, height: 40, borderRadius: 12, background: 'var(--green-tint)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <ModeIcon size={20} color="var(--green-700)" strokeWidth={1.75} />
                </span>
                <span className="ui" style={{ fontSize: 14, fontWeight: 700, color: 'var(--ink)' }}>{mode.label}</span>
                <span className="body-text" style={{ fontSize: 11.5, lineHeight: 1.5, color: 'var(--ink-2)' }}>{mode.blurb}</span>
              </button>
            )
          })}
        </div>

        {/* Deep Dive — full width 5th card */}
        <button
          onClick={() => router.push('/explain')}
          className="v2-card tap"
          style={{ width: '100%', textAlign: 'left', borderRadius: 18, padding: '14px 16px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 13, border: 'none', marginTop: 11 }}
        >
          <span style={{ width: 40, height: 40, borderRadius: 12, background: 'var(--green-tint)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
            <BookOpen size={20} color="var(--green-700)" strokeWidth={1.75} />
          </span>
          <div>
            <div className="ui" style={{ fontSize: 14, fontWeight: 700, color: 'var(--ink)' }}>Deep Dive</div>
            <div className="body-text" style={{ fontSize: 11.5, color: 'var(--ink-2)', marginTop: 2 }}>Structured tutoring grounded in your garden.</div>
          </div>
        </button>

        {/* Ideas ready to develop */}
        {ideas.length > 0 && (
          <>
            <SectionHeader action="See all" onAction={() => router.push('/garden')}>Ideas ready to develop</SectionHeader>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
              {ideas.map((seed) => {
                const paper = isPaperSeed(seed)
                const meta = seed.seed_metadata || seed.metadata || {}
                const pdfUrl = paperPdfUrl(meta)
                return (
                  <div key={seed.id || seed.notion_id} onClick={() => setSelectedIdea(seed)} className="v2-card tap" style={{ borderRadius: 15, padding: '12px 14px', display: 'flex', alignItems: 'center', gap: 12, cursor: 'pointer' }}>
                    {paper ? <BookOpen size={18} color="var(--green-700)" strokeWidth={1.75} style={{ flexShrink: 0 }} /> : <Leaf size={18} color="var(--green-700)" strokeWidth={1.75} style={{ flexShrink: 0 }} />}
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <span className="ui" style={{ display: 'block', fontSize: 13, fontWeight: 500, color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                        {seed.title || 'Untitled'}
                      </span>
                      {paper && (
                        <span style={{ display: 'flex', alignItems: 'center', gap: 7, marginTop: 3 }}>
                          <span className="ui" style={{ fontSize: 8.5, fontWeight: 700, letterSpacing: '0.07em', color: 'var(--green-700)', background: 'var(--green-tint)', borderRadius: 9999, padding: '1.5px 7px' }}>PAPER</span>
                          {pdfUrl && (
                            <a href={pdfUrl} target="_blank" rel="noopener noreferrer" onClick={(e) => e.stopPropagation()} className="ui" style={{ fontSize: 10, fontWeight: 600, color: 'var(--green-700)', textDecoration: 'none' }}>PDF ↗</a>
                          )}
                        </span>
                      )}
                    </div>
                    <button
                      onClick={(e) => { e.stopPropagation(); developSeed(seed) }}
                      className="tap ui"
                      style={{ display: 'flex', alignItems: 'center', gap: 5, background: 'var(--green-tint)', color: 'var(--green-700)', border: 'none', borderRadius: 99, padding: '7px 12px', fontSize: 11.5, fontWeight: 700, cursor: 'pointer', flexShrink: 0 }}
                    >
                      <Pencil size={13} color="var(--green-700)" strokeWidth={2} /> Spec it
                    </button>
                  </div>
                )
              })}
            </div>
          </>
        )}

        {/* Build pipeline — PRDs from Design to Doing to Built */}
        <SectionHeader action="New spec" onAction={() => router.push('/chat?mode=spec')}>Build pipeline</SectionHeader>

        {!loading && prds.length > 0 && (
          <div style={{ marginBottom: 12 }}>
            <Segmented
              value={prdView}
              onChange={(k) => setPrdView(k as 'board' | 'list')}
              items={[
                { key: 'board', label: 'Board', Icon: LayoutGrid },
                { key: 'list', label: 'List', Icon: List },
              ]}
            />
          </div>
        )}

        {loading ? (
          <div style={{ display: 'grid', gridTemplateColumns: 'var(--desk-cols-3)', gap: 12 }}>
            {[1,2,3].map(i => <div key={i} style={{ height: 140, borderRadius: 18, background: 'var(--surface-sunk)', animation: 'pulse 1.5s ease-in-out infinite' }} />)}
          </div>
        ) : prds.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '32px 0', color: 'var(--ink-3)' }}>
            <FileText size={36} strokeWidth={1} color="var(--ink-3)" style={{ margin: '0 auto 10px' }} />
            <p className="ui" style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink-2)' }}>No specs yet</p>
            <p className="body-text" style={{ fontSize: 12, marginTop: 4 }}>Use "Spec it" mode to build a structured PRD</p>
            <button onClick={() => router.push('/chat?mode=spec')} className="tap" style={{ marginTop: 14, background: 'var(--green)', color: '#fff', border: 'none', borderRadius: 9999, padding: '10px 20px', fontFamily: 'var(--ui)', fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>
              Start speccing
            </button>
          </div>
        ) : prdView === 'board' ? (
          <>
          <div style={{ display: 'grid', gridTemplateColumns: 'var(--desk-cols-3)', gap: 12, alignItems: 'start' }}>
            {BOARD_COLUMNS.map((col) => {
              const cards = prds.filter(p => col.statuses.includes(p.buildStatus || 'draft'))
              const isOver = dragOverCol === col.key
              return (
                <div
                  key={col.key}
                  onDragOver={(e) => { e.preventDefault(); setDragOverCol(col.key) }}
                  onDragLeave={() => setDragOverCol(c => (c === col.key ? null : c))}
                  onDrop={(e) => {
                    e.preventDefault()
                    setDragOverCol(null)
                    const id = e.dataTransfer.getData('text/prd-id')
                    const prd = id ? prds.find(p => p.id === id) : undefined
                    if (prd && !prd.local && !col.statuses.includes(prd.buildStatus || 'draft')) {
                      updatePrdStatus(id, col.dropStatus)
                    }
                  }}
                  style={{
                    borderRadius: 18, padding: 10, minHeight: 150,
                    background: isOver ? 'var(--green-tint)' : 'var(--surface-2)',
                    border: isOver ? '1.5px dashed var(--green)' : '1.5px solid var(--hairline)',
                    transition: 'background 0.15s ease, border 0.15s ease',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '4px 6px 10px' }}>
                    <span style={{ width: 8, height: 8, borderRadius: 99, background: col.accent }} />
                    <span className="ui" style={{ fontSize: 12, fontWeight: 700, color: 'var(--ink)' }}>{col.label}</span>
                    <span className="ui" style={{ fontSize: 10.5, fontWeight: 600, color: 'var(--ink-3)', marginLeft: 'auto' }}>{cards.length}</span>
                  </div>
                  {cards.length === 0 ? (
                    <p className="body-text" style={{ fontSize: 11, color: 'var(--ink-3)', textAlign: 'center', padding: '22px 8px' }}>
                      {col.key === 'ready' ? 'Drag a draft here when it’s ready' : 'Drag a spec here'}
                    </p>
                  ) : cards.map((prd) => (
                    <div
                      key={prd.id}
                      draggable={!prd.local}
                      onDragStart={(e) => e.dataTransfer.setData('text/prd-id', prd.id)}
                      onClick={() => setSelected(prd)}
                      className="v2-card tap"
                      style={{ borderRadius: 14, padding: '11px 12px', cursor: prd.local ? 'pointer' : 'grab', marginBottom: 8 }}
                    >
                      <div className="ui" style={{ fontSize: 12.5, fontWeight: 700, color: 'var(--ink)', lineHeight: 1.35 }}>{prd.title}</div>
                      <div className="body-text" style={{ fontSize: 11, color: 'var(--ink-2)', lineHeight: 1.5, marginTop: 3, overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' }}>
                        {prd.content.replace(/^#+\s.*/gm, '').slice(0, 100)}
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginTop: 8 }}>
                        {prd.local ? (
                          <span className="ui" style={{ fontSize: 9, fontWeight: 700, letterSpacing: '0.06em', color: 'var(--ink-3)', background: 'var(--surface-sunk)', borderRadius: 9999, padding: '2px 7px' }}>LOCAL DRAFT</span>
                        ) : prd.buildStatus === 'ready' && (
                          <span className="ui" style={{ fontSize: 9, fontWeight: 700, letterSpacing: '0.06em', color: 'var(--green-700)', background: 'var(--green-tint)', borderRadius: 9999, padding: '2px 7px' }}>READY</span>
                        )}
                        {prd.diagramUrl && <Network size={11} color="var(--ink-3)" strokeWidth={1.75} />}
                        {prd.prUrl && (
                          <a href={prd.prUrl} target="_blank" rel="noopener noreferrer" onClick={(e) => e.stopPropagation()} className="ui" style={{ fontSize: 10, fontWeight: 600, color: 'var(--green-700)', textDecoration: 'none' }}>PR →</a>
                        )}
                        <span className="body-text" style={{ fontSize: 10, color: 'var(--ink-3)', marginLeft: 'auto' }}>{timeAgo(prd.createdAt)}</span>
                      </div>
                    </div>
                  ))}
                </div>
              )
            })}
          </div>

          {/* Drafts — off the canvas, drag onto the board when ready */}
          {prds.some(isDraft) && (
            <div style={{ marginTop: 14 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 8 }}>
                <span style={{ width: 8, height: 8, borderRadius: 99, background: 'var(--ink-3)' }} />
                <span className="ui" style={{ fontSize: 12, fontWeight: 700, color: 'var(--ink-2)' }}>Drafts</span>
                <span className="ui" style={{ fontSize: 10.5, fontWeight: 600, color: 'var(--ink-3)' }}>{prds.filter(isDraft).length}</span>
                <span className="body-text" style={{ fontSize: 10.5, color: 'var(--ink-3)', marginLeft: 6 }}>drag onto the board when ready</span>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'var(--desk-cols-3)', gap: 9 }}>
                {prds.filter(isDraft).map((prd) => (
                  <div
                    key={prd.id}
                    draggable={!prd.local}
                    onDragStart={(e) => e.dataTransfer.setData('text/prd-id', prd.id)}
                    onClick={() => setSelected(prd)}
                    className="v2-card tap"
                    style={{ borderRadius: 13, padding: '10px 12px', cursor: prd.local ? 'pointer' : 'grab', display: 'flex', alignItems: 'center', gap: 9 }}
                  >
                    <FileText size={15} color="var(--ink-3)" strokeWidth={1.75} style={{ flexShrink: 0 }} />
                    <span className="ui" style={{ flex: 1, fontSize: 12, fontWeight: 600, color: 'var(--ink)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{prd.title}</span>
                    {prd.autoGenerated && prd.visionStatus !== 'shaped' && (
                      <button
                        onClick={(e) => { e.stopPropagation(); shapeVision(prd, router) }}
                        className="tap ui"
                        style={{ display: 'flex', alignItems: 'center', gap: 4, background: 'var(--green-tint)', color: 'var(--green-700)', border: 'none', borderRadius: 9999, padding: '4px 9px', fontSize: 10, fontWeight: 700, cursor: 'pointer', flexShrink: 0 }}
                      >
                        <Sparkles size={11} strokeWidth={2} /> Shape
                      </button>
                    )}
                    {prd.autoGenerated && (
                      <span className="ui" style={{ fontSize: 8.5, fontWeight: 700, letterSpacing: '0.06em', color: 'var(--green-700)', background: 'var(--green-tint)', borderRadius: 9999, padding: '2px 6px', flexShrink: 0 }}>AUTO</span>
                    )}
                    {prd.local && <span className="ui" style={{ fontSize: 8.5, fontWeight: 700, letterSpacing: '0.06em', color: 'var(--ink-3)', background: 'var(--surface-sunk)', borderRadius: 9999, padding: '2px 6px', flexShrink: 0 }}>LOCAL</span>}
                  </div>
                ))}
              </div>
            </div>
          )}
          </>
        ) : (
          <div style={{ display: 'grid', gridTemplateColumns: 'var(--desk-cols-2)', gap: 9 }}>
            {(showAllPrds ? prds : prds.slice(0, PRD_PAGE_SIZE)).map((prd) => (
              <div key={prd.id} onClick={() => setSelected(prd)} className="v2-card tap" style={{ borderRadius: 16, padding: 14, display: 'flex', gap: 12, cursor: 'pointer' }}>
                <span style={{ width: 40, height: 40, borderRadius: 12, flexShrink: 0, background: 'var(--green-tint)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <FileText size={19} color="var(--green-700)" strokeWidth={1.75} />
                </span>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div className="ui" style={{ fontSize: 13.5, fontWeight: 700, color: 'var(--ink)' }}>{prd.title}</div>
                  <div className="body-text" style={{ fontSize: 11.5, color: 'var(--ink-2)', lineHeight: 1.5, marginTop: 3, overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' }}>
                    {prd.content.replace(/^#+\s.*/gm, '').slice(0, 120)}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 8 }}>
                    <Pill tone="soft" size="xs">SPEC</Pill>
                    {prd.buildStatus && prd.buildStatus !== 'draft' && (
                      <span className="ui" style={{ fontSize: 9.5, fontWeight: 700, letterSpacing: '0.06em', color: prd.buildStatus === 'shipped' ? '#fff' : 'var(--green-700)', background: prd.buildStatus === 'shipped' ? 'var(--green)' : 'var(--green-tint)', borderRadius: 9999, padding: '2px 8px' }}>
                        {BUILD_STATUS_LABELS[prd.buildStatus]}
                      </span>
                    )}
                    {prd.diagramUrl && <Network size={12} color="var(--ink-3)" strokeWidth={1.75} />}
                    <span className="body-text" style={{ fontSize: 10.5, color: 'var(--ink-3)' }}>{timeAgo(prd.createdAt)}</span>
                  </div>
                </div>
              </div>
            ))}
            {!showAllPrds && prds.length > PRD_PAGE_SIZE && (
              <button onClick={() => setShowAllPrds(true)} className="tap" style={{ width: '100%', padding: '11px', background: 'var(--surface-sunk)', border: '1px solid var(--hairline)', borderRadius: 14, fontFamily: 'var(--ui)', fontSize: 12.5, fontWeight: 600, color: 'var(--ink-2)', cursor: 'pointer' }}>
                Show all {prds.length} specs
              </button>
            )}
          </div>
        )}
      </div>

      <BottomNav />
      <style>{`@keyframes pulse { 0%,100% { opacity: 0.6; } 50% { opacity: 1; } }`}</style>
    </div>
  )
}
